name: torchy
channels:
    - conda-forge
dependencies:
    - python
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - ipykernel
    - ipython
    - ipywidgets
    - torchdiffeq
    - torchsde
